### ISSUE TITLE
software archive doi

### ISSUE THREAD

**Issue by gboeing** [CameronDevine/StateModelRnD#10]
With regards to https://github.com/openjournals/jose-reviews/issues/44

Is the software archived with a DOI (somewhere like zenodo) and documented accordingly in `paper.md`? I don't see it.

**Comment by CameronDevine** [comment]
I will use Zenodo to get a DOI number once all the other issues have been solved and the paper is ready to be published.

**Comment by moorepants** [comment]
DOI is there now: 10.5281/zenodo.2633330
